-- 0006_copilot_prep.sql
-- CSM Co-Pilot prep: NPS submissions, computed health scores, and alerts.
-- Shells-only for V1; CSM Co-Pilot will populate and read these in weeks 4-5.

-- ---------------------------------------------------------------------------
-- nps_submissions
-- ---------------------------------------------------------------------------
create table nps_submissions (
  id              uuid primary key default gen_random_uuid(),
  client_id       uuid not null references clients(id),
  score           integer not null check (score >= 0 and score <= 10),
  feedback        text,
  survey_source   text,
  submitted_at    timestamptz not null,
  ingested_at     timestamptz not null default now()
);

comment on table nps_submissions is
  'NPS scores and free-text feedback from clients. Populated by ingestion (Slack Workflow or survey tool).';
comment on column nps_submissions.score is
  '0-10 NPS score. Check constraint enforces the range.';
comment on column nps_submissions.survey_source is
  'Where the submission came from: slack_workflow, typeform, etc.';
comment on column nps_submissions.submitted_at is
  'When the client submitted the response. Distinct from ingested_at so we can reason about freshness separately from capture lag.';

create index nps_submissions_client_id_submitted_at_idx on nps_submissions (client_id, submitted_at desc);
create index nps_submissions_score_idx on nps_submissions (score);

alter table nps_submissions enable row level security;

-- ---------------------------------------------------------------------------
-- client_health_scores
-- ---------------------------------------------------------------------------
create table client_health_scores (
  id                  uuid primary key default gen_random_uuid(),
  client_id           uuid not null references clients(id),
  score               integer not null check (score >= 0 and score <= 100),
  tier                text not null,
  factors             jsonb not null,
  computed_at         timestamptz not null default now(),
  computed_by_run_id  uuid references agent_runs(id)
);

comment on table client_health_scores is
  'Historical client health scores computed by CSM Co-Pilot. One row per client per computation run — history is preserved.';
comment on column client_health_scores.score is
  '0-100 health score. Range enforced by check constraint.';
comment on column client_health_scores.tier is
  'green, yellow, red. Derived from score + rules at computation time; stored for fast dashboard filtering.';
comment on column client_health_scores.factors is
  'Breakdown of what fed the score: signals, weights, and contributions. Schema determined by CSM Co-Pilot.';
comment on column client_health_scores.computed_by_run_id is
  'Links back to the agent_runs row that produced this score for full traceability.';

create index client_health_scores_client_id_computed_at_idx on client_health_scores (client_id, computed_at desc);
create index client_health_scores_tier_idx on client_health_scores (tier);
create index client_health_scores_computed_by_run_id_idx on client_health_scores (computed_by_run_id)
  where computed_by_run_id is not null;

alter table client_health_scores enable row level security;

-- ---------------------------------------------------------------------------
-- alerts
-- ---------------------------------------------------------------------------
create table alerts (
  id                 uuid primary key default gen_random_uuid(),
  client_id          uuid references clients(id),
  team_member_id     uuid references team_members(id),
  alert_type         text not null,
  severity           text not null,
  title              text not null,
  description        text not null,
  context            jsonb,
  status             text not null default 'open',
  created_by_run_id  uuid references agent_runs(id),
  acknowledged_at    timestamptz,
  resolved_at        timestamptz,
  created_at         timestamptz not null default now()
);

comment on table alerts is
  'Actionable alerts generated by CSM Co-Pilot or other agents. Surfaced to team members in Slack and dashboards.';
comment on column alerts.client_id is
  'Client the alert is about. Nullable for system-level alerts that are not client-scoped.';
comment on column alerts.team_member_id is
  'Who should act on this alert. Usually the primary CSM; null if unassigned and routing is deferred.';
comment on column alerts.alert_type is
  'churn_risk, upsell_opportunity, referral_opportunity, refund_risk, nps_detractor, stalled_progress, etc.';
comment on column alerts.severity is
  'low, medium, high, critical. Drives routing and notification channel.';
comment on column alerts.context is
  'Evidence and reasoning behind the alert. Shape varies per alert_type.';
comment on column alerts.status is
  'open, acknowledged, resolved, dismissed.';
comment on column alerts.created_by_run_id is
  'Links the alert back to the agent_runs row that generated it.';

create index alerts_client_id_status_idx on alerts (client_id, status);
create index alerts_team_member_id_status_idx on alerts (team_member_id, status);
create index alerts_status_severity_idx on alerts (status, severity);
create index alerts_type_idx on alerts (alert_type);
create index alerts_created_at_idx on alerts (created_at desc);

alter table alerts enable row level security;
