-- 0152 — AI intelligence synthesis tables (Nabeel 2026-08-18, phase 4).
--
-- Two LLM-over-aggregates outputs, both DASHBOARD-only by decision (Drake
-- 2026-08-18 — no Slack delivery for these; the per-call review keeps its
-- existing Slack routing):
--
--   dc_ads_exec_summaries — one row per ET day: the executive summary the
--     DC Ads page renders (what's working / what's wrong / traffic-or-sales
--     verdict / what changed / what to test). Generated by
--     api/dc_exec_summary_cron.py (daily, after the ET day closes) from the
--     daily-table rows + call-review aggregates — the model sees ONLY
--     aggregates, never raw transcripts.
--
--   dc_rep_coaching — one row per (ET week, rep): aggregated strengths /
--     weaknesses (from the reviews' quote-evidenced items) + 2-3 coaching
--     recommendations. Generated by api/dc_rep_coaching_cron.py (weekly,
--     Monday early AM, covering the prior Mon-Sun ET week). Rendered on the
--     Connected Calls subpage.
--
-- Same hard isolation as setter_call_reviews (0054): sales-side only, no
-- embeddings, never retrievable by Ella / CS surfaces; LLM cost columns
-- inline, no agent_runs writes.

create table dc_ads_exec_summaries (
  for_date date primary key,
  -- {goingWell: [..], goingWrong: [..], trafficOrSales: "..",
  --  changed: [..], testNext: [..]} — short strings, validated by the
  -- generator (agents/dc_intel/exec_summary.py).
  summary jsonb not null,
  model text not null,
  prompt_version text not null,
  input_tokens integer,
  output_tokens integer,
  cost_usd numeric(10, 6),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table dc_ads_exec_summaries is
  'Daily AI executive summary for the DC Ads page (0152). One row per ET day; regenerating a day is an upsert (prompt iteration). Dashboard-only — not posted to Slack. Sales-side only, not retrievable by Ella.';

create trigger dc_ads_exec_summaries_set_updated_at
  before update on dc_ads_exec_summaries
  for each row execute function set_updated_at();

create table dc_rep_coaching (
  week_start date not null,          -- Monday of the ET week covered
  close_user_id text not null,       -- close_calls.user_id (rep identity)
  rep_name text not null,            -- display fallback frozen at generation
  calls_reviewed integer not null,
  avg_rep_score numeric(4, 1),
  closes integer not null default 0,
  -- Aggregated {point, evidence} items carried from the week's reviews.
  strengths jsonb not null default '[]'::jsonb,
  weaknesses jsonb not null default '[]'::jsonb,
  -- 2-3 {focus, why, drill} coaching recommendations from the synthesis.
  recommendations jsonb not null default '[]'::jsonb,
  model text not null,
  prompt_version text not null,
  input_tokens integer,
  output_tokens integer,
  cost_usd numeric(10, 6),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (week_start, close_user_id)
);

comment on table dc_rep_coaching is
  'Weekly per-rep AI coaching synthesis over dc_ads-rubric call reviews (0152). One row per (ET Monday, rep); regeneration is an upsert. Rendered on the DC Ads Connected Calls subpage. Sales-side only.';

create trigger dc_rep_coaching_set_updated_at
  before update on dc_rep_coaching
  for each row execute function set_updated_at();

create index dc_rep_coaching_week_idx on dc_rep_coaching (week_start desc);
